sudo: required
language: python
python: 3.5

services:
  - docker

cache:
  directories:
    - ~/.cache/pip

install:
      - pip install tox
before_script:
script:
      - tox
      - docker build --tag gnocchi-ci --file=dockerhub/travis-ci-image.dockerfile .
      # Allow docker to write in home directory
      - chmod -R o+w ~/
      - find ~/ -type d -exec chmod o+x {} \;
      - docker run -v ~/.cache/pip:/home/tester/.cache/pip -v $(pwd):/home/tester/src gnocchi-ci tox -epep8
env:
      - TOXENV=py27
      - TOXENV=py35
      - TOXENV=pep8
